# Generated by Django 4.0.1 on 2022-01-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_country_coursetype_districts_states_place_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Districts',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
