# Generated by Django 4.0.1 on 2022-02-04 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MetaData', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('experience', models.IntegerField()),
                ('search_tags', models.CharField(max_length=400)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('resume', models.FileField(upload_to='resumes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetaData.course')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetaData.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
