# Generated by Django 4.0.1 on 2022-02-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='avatar',
            new_name='avatar_image',
        ),
    ]
