# Generated by Django 4.0.1 on 2022-02-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_rename_avatar_employee_avatar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='mail_id',
            new_name='email',
        ),
    ]
