# Generated by Django 4.0.1 on 2022-02-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_rename_dob_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
