# Generated by Django 4.0.1 on 2022-03-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_app_admin',
            field=models.BooleanField(default=False, verbose_name='Is app admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='Is employer'),
        ),
    ]
