# Generated by Django 4.0.1 on 2022-03-26 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_user_is_app_admin_alter_user_is_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logos'),
            preserve_default=False,
        ),
    ]
