# Generated by Django 4.0.1 on 2022-01-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_employee_applyjob_alter_employeeinvite_employee'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
