# Generated by Django 4.0.1 on 2022-01-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinvite',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.employee'),
        ),
        migrations.AddField(
            model_name='employeeinvite',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.employer'),
        ),
        migrations.AddField(
            model_name='employeeinvite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.jobs'),
        ),
    ]
