# Generated by Django 4.0.1 on 2022-02-05 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
