# Generated by Django 4.0.1 on 2022-02-05 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_user_is_staff'),
        ('Employer', '0002_alter_job_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateField(default=datetime.date(2022, 2, 5)),
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.job')),
            ],
        ),
    ]
