# Generated by Django 4.0.1 on 2022-01-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_districts_district_rename_states_state'),
        ('Employer', '0003_employee_applyjob_alter_employeeinvite_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
