# Generated by Django 4.0.1 on 2022-02-06 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_alter_job_post_date_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateField(default=datetime.date(2022, 2, 6)),
        ),
    ]
