# Generated by Django 4.0.1 on 2022-02-06 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0004_alter_job_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
